/**
 * Emoji dataset for the page icon picker.
 *
 * Pre-baked unicode emoji list grouped by category, with search keywords.
 * We do not depend on `emoji-mart` or similar to keep the bundle slim — this
 * list intentionally covers the most-used set, not every codepoint. Add
 * more if power users hit gaps.
 *
 * Skin-tone variants are generated on the fly by appending Fitzpatrick
 * codepoints; entries marked with `tone: true` opt in.
 */

export interface EmojiEntry {
  /** The emoji character (base form, no skin tone). */
  emoji: string;
  /** Lowercased search keywords joined by spaces. */
  keywords: string;
  /** Emoji supports skin-tone modifiers. */
  tone?: boolean;
}

export interface EmojiCategory {
  id: string;
  name: string;
  emojis: ReadonlyArray<EmojiEntry>;
}

/** Fitzpatrick skin-tone modifier codepoints. */
export const SKIN_TONES: ReadonlyArray<{ id: string; label: string; modifier: string }> = [
  { id: "default", label: "Default", modifier: "" },
  { id: "light", label: "Light", modifier: "\u{1F3FB}" },
  { id: "medium-light", label: "Medium light", modifier: "\u{1F3FC}" },
  { id: "medium", label: "Medium", modifier: "\u{1F3FD}" },
  { id: "medium-dark", label: "Medium dark", modifier: "\u{1F3FE}" },
  { id: "dark", label: "Dark", modifier: "\u{1F3FF}" },
];

/**
 * Apply a Fitzpatrick modifier to an emoji that supports skin tones. For
 * emojis that don't, returns the base emoji unchanged.
 */
export function applySkinTone(entry: EmojiEntry, modifier: string): string {
  if (!entry.tone || !modifier) return entry.emoji;
  return `${entry.emoji}${modifier}`;
}

/* eslint-disable max-lines */
export const EMOJI_CATEGORIES: ReadonlyArray<EmojiCategory> = [
  {
    id: "smileys",
    name: "Smileys & People",
    emojis: [
      { emoji: "😀", keywords: "grinning face smile happy" },
      { emoji: "😃", keywords: "grinning big eyes smile" },
      { emoji: "😄", keywords: "grinning smile open mouth" },
      { emoji: "😁", keywords: "beaming face grin smile" },
      { emoji: "😆", keywords: "laughing smile lol" },
      { emoji: "😅", keywords: "grinning sweat smile" },
      { emoji: "🤣", keywords: "rofl laugh roll floor" },
      { emoji: "😂", keywords: "laughing tears joy" },
      { emoji: "🙂", keywords: "slight smile" },
      { emoji: "🙃", keywords: "upside down face" },
      { emoji: "😉", keywords: "winking face wink" },
      { emoji: "😊", keywords: "smiling face blush happy" },
      { emoji: "😇", keywords: "halo angel innocent" },
      { emoji: "🥰", keywords: "smiling face hearts love" },
      { emoji: "😍", keywords: "heart eyes love" },
      { emoji: "🤩", keywords: "star struck eyes" },
      { emoji: "😘", keywords: "blowing kiss" },
      { emoji: "😗", keywords: "kissing face" },
      { emoji: "😚", keywords: "kissing closed eyes" },
      { emoji: "😙", keywords: "kissing smile" },
      { emoji: "🥲", keywords: "smile tear happy sad" },
      { emoji: "😋", keywords: "savoring food yum" },
      { emoji: "😛", keywords: "tongue out face" },
      { emoji: "😜", keywords: "winking tongue out" },
      { emoji: "🤪", keywords: "zany crazy" },
      { emoji: "😝", keywords: "squinting tongue" },
      { emoji: "🤑", keywords: "money mouth" },
      { emoji: "🤗", keywords: "hugging face" },
      { emoji: "🤭", keywords: "hand over mouth" },
      { emoji: "🤫", keywords: "shushing quiet" },
      { emoji: "🤔", keywords: "thinking face" },
      { emoji: "🤐", keywords: "zipper mouth secret" },
      { emoji: "🤨", keywords: "face raised eyebrow" },
      { emoji: "😐", keywords: "neutral face" },
      { emoji: "😑", keywords: "expressionless face" },
      { emoji: "😶", keywords: "no mouth face" },
      { emoji: "😏", keywords: "smirking face" },
      { emoji: "😒", keywords: "unamused face" },
      { emoji: "🙄", keywords: "rolling eyes" },
      { emoji: "😬", keywords: "grimacing face" },
      { emoji: "🤥", keywords: "lying face nose" },
      { emoji: "😌", keywords: "relieved face" },
      { emoji: "😔", keywords: "pensive face" },
      { emoji: "😪", keywords: "sleepy tired" },
      { emoji: "🤤", keywords: "drooling face" },
      { emoji: "😴", keywords: "sleeping face zzz" },
      { emoji: "😷", keywords: "mask face sick" },
      { emoji: "🤒", keywords: "thermometer sick" },
      { emoji: "🤕", keywords: "head bandage hurt" },
      { emoji: "🤢", keywords: "nauseated face green" },
      { emoji: "🤮", keywords: "vomiting face" },
      { emoji: "🤧", keywords: "sneezing face" },
      { emoji: "🥵", keywords: "hot face sweat" },
      { emoji: "🥶", keywords: "cold face freezing" },
      { emoji: "🥴", keywords: "woozy face drunk" },
      { emoji: "😵", keywords: "dizzy face" },
      { emoji: "🤯", keywords: "exploding head mind blown" },
      { emoji: "🤠", keywords: "cowboy hat" },
      { emoji: "🥳", keywords: "party face hat" },
      { emoji: "😎", keywords: "cool sunglasses smile" },
      { emoji: "🤓", keywords: "nerd face glasses" },
      { emoji: "🧐", keywords: "monocle face" },
      { emoji: "😕", keywords: "confused face" },
      { emoji: "😟", keywords: "worried face" },
      { emoji: "🙁", keywords: "frowning face slight" },
      { emoji: "☹️", keywords: "frowning face" },
      { emoji: "😮", keywords: "open mouth face" },
      { emoji: "😯", keywords: "hushed face" },
      { emoji: "😲", keywords: "astonished face" },
      { emoji: "😳", keywords: "flushed face" },
      { emoji: "🥺", keywords: "pleading face puppy" },
      { emoji: "😦", keywords: "frowning open mouth" },
      { emoji: "😧", keywords: "anguished face" },
      { emoji: "😨", keywords: "fearful face" },
      { emoji: "😰", keywords: "anxious face sweat" },
      { emoji: "😥", keywords: "sad face sweat" },
      { emoji: "😢", keywords: "crying tear" },
      { emoji: "😭", keywords: "loudly crying tears" },
      { emoji: "😱", keywords: "screaming fear" },
      { emoji: "😖", keywords: "confounded face" },
      { emoji: "😣", keywords: "persevering face" },
      { emoji: "😞", keywords: "disappointed face" },
      { emoji: "😓", keywords: "downcast sweat" },
      { emoji: "😩", keywords: "weary face" },
      { emoji: "😫", keywords: "tired face" },
      { emoji: "🥱", keywords: "yawning face" },
      { emoji: "😤", keywords: "huffing face steam" },
      { emoji: "😡", keywords: "pouting face rage" },
      { emoji: "😠", keywords: "angry face" },
      { emoji: "🤬", keywords: "swearing face" },
      { emoji: "😈", keywords: "smiling devil purple" },
      { emoji: "👿", keywords: "angry devil" },
      { emoji: "💀", keywords: "skull death" },
      { emoji: "👻", keywords: "ghost spooky" },
      { emoji: "👽", keywords: "alien ufo" },
      { emoji: "🤖", keywords: "robot face" },
      { emoji: "👋", keywords: "wave hand hello", tone: true },
      { emoji: "👍", keywords: "thumbs up like", tone: true },
      { emoji: "👎", keywords: "thumbs down dislike", tone: true },
      { emoji: "👏", keywords: "clap hands applause", tone: true },
      { emoji: "🙌", keywords: "raising hands praise", tone: true },
      { emoji: "🙏", keywords: "praying hands thanks", tone: true },
      { emoji: "💪", keywords: "muscle strong", tone: true },
      { emoji: "✌️", keywords: "victory peace", tone: true },
      { emoji: "🤘", keywords: "rock hand horns", tone: true },
      { emoji: "👌", keywords: "ok hand", tone: true },
      { emoji: "🤞", keywords: "fingers crossed luck", tone: true },
      { emoji: "👈", keywords: "point left", tone: true },
      { emoji: "👉", keywords: "point right", tone: true },
      { emoji: "👆", keywords: "point up", tone: true },
      { emoji: "👇", keywords: "point down", tone: true },
    ],
  },
  {
    id: "animals",
    name: "Animals & Nature",
    emojis: [
      { emoji: "🐶", keywords: "dog face pet animal" },
      { emoji: "🐱", keywords: "cat face pet" },
      { emoji: "🐭", keywords: "mouse face" },
      { emoji: "🐹", keywords: "hamster face" },
      { emoji: "🐰", keywords: "rabbit face bunny" },
      { emoji: "🦊", keywords: "fox face" },
      { emoji: "🐻", keywords: "bear face" },
      { emoji: "🐼", keywords: "panda face" },
      { emoji: "🐨", keywords: "koala face" },
      { emoji: "🐯", keywords: "tiger face" },
      { emoji: "🦁", keywords: "lion face" },
      { emoji: "🐮", keywords: "cow face" },
      { emoji: "🐷", keywords: "pig face" },
      { emoji: "🐸", keywords: "frog face" },
      { emoji: "🐵", keywords: "monkey face" },
      { emoji: "🙈", keywords: "see no evil monkey" },
      { emoji: "🙉", keywords: "hear no evil monkey" },
      { emoji: "🙊", keywords: "speak no evil monkey" },
      { emoji: "🐔", keywords: "chicken face" },
      { emoji: "🐧", keywords: "penguin face" },
      { emoji: "🐦", keywords: "bird face" },
      { emoji: "🐤", keywords: "baby chick face" },
      { emoji: "🦆", keywords: "duck face" },
      { emoji: "🦅", keywords: "eagle face" },
      { emoji: "🦉", keywords: "owl face" },
      { emoji: "🦇", keywords: "bat face" },
      { emoji: "🐺", keywords: "wolf face" },
      { emoji: "🐗", keywords: "boar face" },
      { emoji: "🐴", keywords: "horse face" },
      { emoji: "🦄", keywords: "unicorn face" },
      { emoji: "🐝", keywords: "bee insect" },
      { emoji: "🐛", keywords: "bug caterpillar" },
      { emoji: "🦋", keywords: "butterfly insect" },
      { emoji: "🐌", keywords: "snail" },
      { emoji: "🐞", keywords: "ladybug insect" },
      { emoji: "🐢", keywords: "turtle" },
      { emoji: "🐍", keywords: "snake" },
      { emoji: "🦎", keywords: "lizard reptile" },
      { emoji: "🦖", keywords: "trex dinosaur" },
      { emoji: "🐙", keywords: "octopus" },
      { emoji: "🦑", keywords: "squid" },
      { emoji: "🦀", keywords: "crab" },
      { emoji: "🐟", keywords: "fish" },
      { emoji: "🐠", keywords: "tropical fish" },
      { emoji: "🐡", keywords: "blowfish puffer" },
      { emoji: "🐬", keywords: "dolphin" },
      { emoji: "🦈", keywords: "shark" },
      { emoji: "🐳", keywords: "spouting whale" },
      { emoji: "🐊", keywords: "crocodile reptile" },
      { emoji: "🐘", keywords: "elephant" },
      { emoji: "🦒", keywords: "giraffe" },
      { emoji: "🐫", keywords: "two-hump camel" },
      { emoji: "🦘", keywords: "kangaroo" },
      { emoji: "🐎", keywords: "horse" },
      { emoji: "🌵", keywords: "cactus plant" },
      { emoji: "🌲", keywords: "evergreen tree" },
      { emoji: "🌳", keywords: "deciduous tree" },
      { emoji: "🌴", keywords: "palm tree" },
      { emoji: "🌱", keywords: "seedling plant" },
      { emoji: "🌿", keywords: "herb plant" },
      { emoji: "🍀", keywords: "four leaf clover luck" },
      { emoji: "🍁", keywords: "maple leaf" },
      { emoji: "🍂", keywords: "fallen leaf autumn" },
      { emoji: "🌷", keywords: "tulip flower" },
      { emoji: "🌹", keywords: "rose flower" },
      { emoji: "🌻", keywords: "sunflower" },
      { emoji: "🌼", keywords: "blossom flower" },
      { emoji: "🌸", keywords: "cherry blossom flower" },
      { emoji: "💐", keywords: "bouquet flowers" },
    ],
  },
  {
    id: "food",
    name: "Food & Drink",
    emojis: [
      { emoji: "🍎", keywords: "red apple fruit" },
      { emoji: "🍏", keywords: "green apple fruit" },
      { emoji: "🍐", keywords: "pear fruit" },
      { emoji: "🍊", keywords: "orange tangerine fruit" },
      { emoji: "🍋", keywords: "lemon fruit" },
      { emoji: "🍌", keywords: "banana fruit" },
      { emoji: "🍉", keywords: "watermelon fruit" },
      { emoji: "🍇", keywords: "grapes fruit" },
      { emoji: "🍓", keywords: "strawberry fruit" },
      { emoji: "🍈", keywords: "melon fruit" },
      { emoji: "🍒", keywords: "cherries fruit" },
      { emoji: "🍑", keywords: "peach fruit" },
      { emoji: "🥭", keywords: "mango fruit" },
      { emoji: "🍍", keywords: "pineapple fruit" },
      { emoji: "🥥", keywords: "coconut" },
      { emoji: "🥝", keywords: "kiwi fruit" },
      { emoji: "🍅", keywords: "tomato" },
      { emoji: "🍆", keywords: "eggplant aubergine" },
      { emoji: "🥑", keywords: "avocado" },
      { emoji: "🥦", keywords: "broccoli" },
      { emoji: "🥬", keywords: "leafy green" },
      { emoji: "🥒", keywords: "cucumber" },
      { emoji: "🌶️", keywords: "hot pepper chili" },
      { emoji: "🌽", keywords: "corn" },
      { emoji: "🥕", keywords: "carrot" },
      { emoji: "🥔", keywords: "potato" },
      { emoji: "🍠", keywords: "roasted sweet potato" },
      { emoji: "🥐", keywords: "croissant bread" },
      { emoji: "🥯", keywords: "bagel bread" },
      { emoji: "🍞", keywords: "bread loaf" },
      { emoji: "🥖", keywords: "baguette bread" },
      { emoji: "🥨", keywords: "pretzel" },
      { emoji: "🧀", keywords: "cheese wedge" },
      { emoji: "🥚", keywords: "egg" },
      { emoji: "🍳", keywords: "egg cooking" },
      { emoji: "🥞", keywords: "pancakes" },
      { emoji: "🧇", keywords: "waffle" },
      { emoji: "🥓", keywords: "bacon" },
      { emoji: "🥩", keywords: "cut of meat" },
      { emoji: "🍗", keywords: "poultry leg" },
      { emoji: "🍖", keywords: "meat on bone" },
      { emoji: "🌭", keywords: "hot dog" },
      { emoji: "🍔", keywords: "burger" },
      { emoji: "🍟", keywords: "french fries" },
      { emoji: "🍕", keywords: "pizza slice" },
      { emoji: "🥪", keywords: "sandwich" },
      { emoji: "🌮", keywords: "taco" },
      { emoji: "🌯", keywords: "burrito" },
      { emoji: "🥙", keywords: "stuffed flatbread" },
      { emoji: "🥗", keywords: "green salad" },
      { emoji: "🍝", keywords: "spaghetti pasta" },
      { emoji: "🍜", keywords: "ramen noodles" },
      { emoji: "🍲", keywords: "pot of food stew" },
      { emoji: "🍣", keywords: "sushi" },
      { emoji: "🍱", keywords: "bento box" },
      { emoji: "🍤", keywords: "fried shrimp" },
      { emoji: "🍙", keywords: "rice ball" },
      { emoji: "🍚", keywords: "cooked rice" },
      { emoji: "🍘", keywords: "rice cracker" },
      { emoji: "🍥", keywords: "fish cake" },
      { emoji: "🥠", keywords: "fortune cookie" },
      { emoji: "🍡", keywords: "dango" },
      { emoji: "🍦", keywords: "soft ice cream" },
      { emoji: "🍨", keywords: "ice cream" },
      { emoji: "🍧", keywords: "shaved ice" },
      { emoji: "🍰", keywords: "shortcake slice" },
      { emoji: "🎂", keywords: "birthday cake" },
      { emoji: "🍮", keywords: "custard pudding" },
      { emoji: "🍭", keywords: "lollipop candy" },
      { emoji: "🍬", keywords: "candy" },
      { emoji: "🍫", keywords: "chocolate bar" },
      { emoji: "🍩", keywords: "donut" },
      { emoji: "🍪", keywords: "cookie" },
      { emoji: "🥛", keywords: "milk" },
      { emoji: "🍼", keywords: "baby bottle milk" },
      { emoji: "☕", keywords: "hot beverage coffee" },
      { emoji: "🍵", keywords: "tea cup" },
      { emoji: "🍶", keywords: "sake" },
      { emoji: "🍾", keywords: "champagne bottle pop" },
      { emoji: "🍷", keywords: "wine glass" },
      { emoji: "🍸", keywords: "cocktail martini" },
      { emoji: "🍹", keywords: "tropical drink" },
      { emoji: "🍺", keywords: "beer mug" },
      { emoji: "🍻", keywords: "beer cheers" },
      { emoji: "🥂", keywords: "clinking glasses cheers" },
      { emoji: "🥃", keywords: "tumbler glass whiskey" },
      { emoji: "🥤", keywords: "cup with straw drink" },
    ],
  },
  {
    id: "activities",
    name: "Activities",
    emojis: [
      { emoji: "⚽", keywords: "soccer ball" },
      { emoji: "🏀", keywords: "basketball" },
      { emoji: "🏈", keywords: "american football" },
      { emoji: "⚾", keywords: "baseball" },
      { emoji: "🥎", keywords: "softball" },
      { emoji: "🎾", keywords: "tennis ball" },
      { emoji: "🏐", keywords: "volleyball" },
      { emoji: "🏉", keywords: "rugby football" },
      { emoji: "🎱", keywords: "pool ball billiards" },
      { emoji: "🪀", keywords: "yo-yo" },
      { emoji: "🏓", keywords: "ping pong" },
      { emoji: "🏸", keywords: "badminton" },
      { emoji: "🏒", keywords: "ice hockey" },
      { emoji: "🏑", keywords: "field hockey" },
      { emoji: "🥍", keywords: "lacrosse" },
      { emoji: "🏏", keywords: "cricket game" },
      { emoji: "⛳", keywords: "golf flag in hole" },
      { emoji: "🏹", keywords: "bow and arrow archery" },
      { emoji: "🎣", keywords: "fishing pole" },
      { emoji: "🥊", keywords: "boxing glove" },
      { emoji: "🥋", keywords: "martial arts uniform" },
      { emoji: "🎽", keywords: "running shirt" },
      { emoji: "🛹", keywords: "skateboard" },
      { emoji: "🛷", keywords: "sled" },
      { emoji: "⛸️", keywords: "ice skate" },
      { emoji: "🥌", keywords: "curling stone" },
      { emoji: "🎿", keywords: "skis" },
      { emoji: "⛷️", keywords: "skier" },
      { emoji: "🏂", keywords: "snowboarder" },
      { emoji: "🪂", keywords: "parachute" },
      { emoji: "🏋️", keywords: "weight lifting", tone: true },
      { emoji: "🤼", keywords: "wrestlers" },
      { emoji: "🤸", keywords: "person cartwheeling", tone: true },
      { emoji: "⛹️", keywords: "person bouncing ball", tone: true },
      { emoji: "🤺", keywords: "fencing" },
      { emoji: "🤾", keywords: "handball", tone: true },
      { emoji: "🏌️", keywords: "golfer", tone: true },
      { emoji: "🏇", keywords: "horse racing", tone: true },
      { emoji: "🧘", keywords: "yoga lotus", tone: true },
      { emoji: "🏄", keywords: "surfer", tone: true },
      { emoji: "🏊", keywords: "swimmer", tone: true },
      { emoji: "🤽", keywords: "water polo", tone: true },
      { emoji: "🚣", keywords: "rowing boat", tone: true },
      { emoji: "🚴", keywords: "biking", tone: true },
      { emoji: "🚵", keywords: "mountain biking", tone: true },
      { emoji: "🎭", keywords: "performing arts theatre" },
      { emoji: "🎨", keywords: "artist palette art" },
      { emoji: "🎬", keywords: "clapper board movie" },
      { emoji: "🎤", keywords: "microphone karaoke" },
      { emoji: "🎧", keywords: "headphone music" },
      { emoji: "🎼", keywords: "musical score" },
      { emoji: "🎵", keywords: "musical note" },
      { emoji: "🎶", keywords: "musical notes" },
      { emoji: "🎹", keywords: "piano" },
      { emoji: "🥁", keywords: "drum" },
      { emoji: "🎷", keywords: "saxophone" },
      { emoji: "🎺", keywords: "trumpet" },
      { emoji: "🎸", keywords: "guitar" },
      { emoji: "🎻", keywords: "violin" },
      { emoji: "🎲", keywords: "game die dice" },
      { emoji: "♟️", keywords: "chess pawn" },
      { emoji: "🎯", keywords: "direct hit bullseye" },
      { emoji: "🎳", keywords: "bowling" },
      { emoji: "🎮", keywords: "video game controller" },
      { emoji: "🎰", keywords: "slot machine" },
      { emoji: "🧩", keywords: "puzzle piece" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Places",
    emojis: [
      { emoji: "🚗", keywords: "automobile car" },
      { emoji: "🚕", keywords: "taxi cab" },
      { emoji: "🚙", keywords: "sport utility vehicle suv" },
      { emoji: "🚌", keywords: "bus" },
      { emoji: "🚎", keywords: "trolleybus" },
      { emoji: "🏎️", keywords: "racing car" },
      { emoji: "🚓", keywords: "police car" },
      { emoji: "🚑", keywords: "ambulance" },
      { emoji: "🚒", keywords: "fire engine" },
      { emoji: "🚐", keywords: "minibus" },
      { emoji: "🚚", keywords: "delivery truck" },
      { emoji: "🚛", keywords: "articulated lorry truck" },
      { emoji: "🚜", keywords: "tractor" },
      { emoji: "🛴", keywords: "kick scooter" },
      { emoji: "🚲", keywords: "bicycle" },
      { emoji: "🛵", keywords: "motor scooter" },
      { emoji: "🏍️", keywords: "motorcycle" },
      { emoji: "🚨", keywords: "police light" },
      { emoji: "🚔", keywords: "oncoming police car" },
      { emoji: "🚍", keywords: "oncoming bus" },
      { emoji: "🚘", keywords: "oncoming car" },
      { emoji: "🚖", keywords: "oncoming taxi" },
      { emoji: "🚡", keywords: "aerial tramway" },
      { emoji: "🚠", keywords: "mountain cableway" },
      { emoji: "🚟", keywords: "suspension railway" },
      { emoji: "🚃", keywords: "railway car" },
      { emoji: "🚋", keywords: "tram car" },
      { emoji: "🚞", keywords: "mountain railway" },
      { emoji: "🚝", keywords: "monorail" },
      { emoji: "🚄", keywords: "high speed train" },
      { emoji: "🚅", keywords: "bullet train" },
      { emoji: "🚈", keywords: "light rail" },
      { emoji: "🚂", keywords: "locomotive train" },
      { emoji: "🚆", keywords: "train" },
      { emoji: "🚇", keywords: "metro subway" },
      { emoji: "🚊", keywords: "tram" },
      { emoji: "🚉", keywords: "station" },
      { emoji: "✈️", keywords: "airplane" },
      { emoji: "🛫", keywords: "airplane departure" },
      { emoji: "🛬", keywords: "airplane arrival" },
      { emoji: "🛩️", keywords: "small airplane" },
      { emoji: "💺", keywords: "seat" },
      { emoji: "🛰️", keywords: "satellite" },
      { emoji: "🚀", keywords: "rocket launch" },
      { emoji: "🛸", keywords: "flying saucer ufo" },
      { emoji: "🚁", keywords: "helicopter" },
      { emoji: "🛶", keywords: "canoe" },
      { emoji: "⛵", keywords: "sailboat" },
      { emoji: "🛥️", keywords: "motor boat" },
      { emoji: "🚤", keywords: "speedboat" },
      { emoji: "🛳️", keywords: "passenger ship" },
      { emoji: "⛴️", keywords: "ferry" },
      { emoji: "🚢", keywords: "ship" },
      { emoji: "⚓", keywords: "anchor" },
      { emoji: "⛽", keywords: "fuel pump gas" },
      { emoji: "🚧", keywords: "construction barrier" },
      { emoji: "🚦", keywords: "vertical traffic light" },
      { emoji: "🚥", keywords: "horizontal traffic light" },
      { emoji: "🗺️", keywords: "world map" },
      { emoji: "🗿", keywords: "moai statue" },
      { emoji: "🗽", keywords: "statue of liberty" },
      { emoji: "🗼", keywords: "tokyo tower" },
      { emoji: "🏰", keywords: "castle" },
      { emoji: "🏯", keywords: "japanese castle" },
      { emoji: "🏟️", keywords: "stadium" },
      { emoji: "🎡", keywords: "ferris wheel" },
      { emoji: "🎢", keywords: "roller coaster" },
      { emoji: "🎠", keywords: "carousel horse" },
      { emoji: "⛲", keywords: "fountain" },
      { emoji: "⛱️", keywords: "umbrella on ground beach" },
      { emoji: "🏖️", keywords: "beach umbrella" },
      { emoji: "🏝️", keywords: "desert island" },
      { emoji: "🏜️", keywords: "desert" },
      { emoji: "🌋", keywords: "volcano" },
      { emoji: "⛰️", keywords: "mountain" },
      { emoji: "🏔️", keywords: "snow mountain" },
      { emoji: "🗻", keywords: "mount fuji" },
      { emoji: "🏕️", keywords: "camping" },
      { emoji: "⛺", keywords: "tent" },
      { emoji: "🏠", keywords: "house" },
      { emoji: "🏡", keywords: "house with garden" },
      { emoji: "🏢", keywords: "office building" },
      { emoji: "🏣", keywords: "japanese post office" },
      { emoji: "🏤", keywords: "post office" },
      { emoji: "🏥", keywords: "hospital" },
      { emoji: "🏦", keywords: "bank" },
      { emoji: "🏨", keywords: "hotel" },
      { emoji: "🏪", keywords: "convenience store" },
      { emoji: "🏫", keywords: "school" },
      { emoji: "🏬", keywords: "department store" },
      { emoji: "🏭", keywords: "factory" },
      { emoji: "🏛️", keywords: "classical building" },
      { emoji: "⛪", keywords: "church" },
      { emoji: "🕌", keywords: "mosque" },
      { emoji: "🛕", keywords: "hindu temple" },
      { emoji: "🕍", keywords: "synagogue" },
      { emoji: "⛩️", keywords: "shinto shrine" },
      { emoji: "💒", keywords: "wedding chapel" },
      { emoji: "🌆", keywords: "cityscape at dusk" },
      { emoji: "🌇", keywords: "sunset over city" },
      { emoji: "🌃", keywords: "night with stars" },
      { emoji: "🌌", keywords: "milky way" },
      { emoji: "🌉", keywords: "bridge at night" },
      { emoji: "🌅", keywords: "sunrise" },
      { emoji: "🌄", keywords: "sunrise over mountains" },
      { emoji: "🌠", keywords: "shooting star" },
      { emoji: "🎇", keywords: "sparkler" },
      { emoji: "🎆", keywords: "fireworks" },
    ],
  },
  {
    id: "objects",
    name: "Objects",
    emojis: [
      { emoji: "⌚", keywords: "watch wrist" },
      { emoji: "📱", keywords: "mobile phone" },
      { emoji: "💻", keywords: "laptop computer" },
      { emoji: "⌨️", keywords: "keyboard" },
      { emoji: "🖥️", keywords: "desktop computer" },
      { emoji: "🖨️", keywords: "printer" },
      { emoji: "🖱️", keywords: "computer mouse" },
      { emoji: "💽", keywords: "minidisk" },
      { emoji: "💾", keywords: "floppy disk" },
      { emoji: "💿", keywords: "cd" },
      { emoji: "📀", keywords: "dvd" },
      { emoji: "📼", keywords: "videocassette" },
      { emoji: "📷", keywords: "camera photo" },
      { emoji: "📸", keywords: "camera flash" },
      { emoji: "📹", keywords: "video camera" },
      { emoji: "🎥", keywords: "movie camera" },
      { emoji: "📽️", keywords: "film projector" },
      { emoji: "🎞️", keywords: "film frames" },
      { emoji: "📞", keywords: "telephone receiver" },
      { emoji: "☎️", keywords: "telephone" },
      { emoji: "📟", keywords: "pager" },
      { emoji: "📠", keywords: "fax machine" },
      { emoji: "📺", keywords: "television tv" },
      { emoji: "📻", keywords: "radio" },
      { emoji: "🎙️", keywords: "studio microphone" },
      { emoji: "🧭", keywords: "compass" },
      { emoji: "⏱️", keywords: "stopwatch" },
      { emoji: "⏲️", keywords: "timer clock" },
      { emoji: "⏰", keywords: "alarm clock" },
      { emoji: "🕰️", keywords: "mantelpiece clock" },
      { emoji: "⌛", keywords: "hourglass done" },
      { emoji: "⏳", keywords: "hourglass not done" },
      { emoji: "📡", keywords: "satellite antenna" },
      { emoji: "🔋", keywords: "battery" },
      { emoji: "🔌", keywords: "electric plug" },
      { emoji: "💡", keywords: "light bulb idea" },
      { emoji: "🔦", keywords: "flashlight" },
      { emoji: "🕯️", keywords: "candle" },
      { emoji: "🪔", keywords: "diya lamp" },
      { emoji: "🧯", keywords: "fire extinguisher" },
      { emoji: "🛢️", keywords: "oil drum" },
      { emoji: "💸", keywords: "money with wings" },
      { emoji: "💵", keywords: "dollar banknote" },
      { emoji: "💴", keywords: "yen banknote" },
      { emoji: "💶", keywords: "euro banknote" },
      { emoji: "💷", keywords: "pound banknote" },
      { emoji: "💰", keywords: "money bag" },
      { emoji: "💳", keywords: "credit card" },
      { emoji: "💎", keywords: "gem stone diamond" },
      { emoji: "⚖️", keywords: "balance scale" },
      { emoji: "🧰", keywords: "toolbox" },
      { emoji: "🔧", keywords: "wrench" },
      { emoji: "🔨", keywords: "hammer" },
      { emoji: "⚒️", keywords: "hammer and pick" },
      { emoji: "🛠️", keywords: "hammer and wrench" },
      { emoji: "⛏️", keywords: "pick" },
      { emoji: "🔩", keywords: "nut and bolt" },
      { emoji: "⚙️", keywords: "gear" },
      { emoji: "🧲", keywords: "magnet" },
      { emoji: "🔫", keywords: "water pistol" },
      { emoji: "💣", keywords: "bomb" },
      { emoji: "🧨", keywords: "firecracker" },
      { emoji: "🔪", keywords: "kitchen knife" },
      { emoji: "🗡️", keywords: "dagger" },
      { emoji: "⚔️", keywords: "crossed swords" },
      { emoji: "🛡️", keywords: "shield" },
      { emoji: "🚬", keywords: "cigarette" },
      { emoji: "⚰️", keywords: "coffin" },
      { emoji: "⚱️", keywords: "funeral urn" },
      { emoji: "🏺", keywords: "amphora" },
      { emoji: "🔮", keywords: "crystal ball" },
      { emoji: "📿", keywords: "prayer beads" },
      { emoji: "🧿", keywords: "nazar amulet" },
      { emoji: "💈", keywords: "barber pole" },
      { emoji: "⚗️", keywords: "alembic chemistry" },
      { emoji: "🔭", keywords: "telescope" },
      { emoji: "🔬", keywords: "microscope" },
      { emoji: "🕳️", keywords: "hole" },
      { emoji: "💊", keywords: "pill" },
      { emoji: "💉", keywords: "syringe" },
      { emoji: "🩸", keywords: "drop of blood" },
      { emoji: "🩹", keywords: "adhesive bandage" },
      { emoji: "🧬", keywords: "dna" },
      { emoji: "🧫", keywords: "petri dish" },
      { emoji: "🧪", keywords: "test tube" },
      { emoji: "🌡️", keywords: "thermometer" },
      { emoji: "🧹", keywords: "broom" },
      { emoji: "🧺", keywords: "basket" },
      { emoji: "🧻", keywords: "roll of paper" },
      { emoji: "🪒", keywords: "razor" },
      { emoji: "🧼", keywords: "soap" },
      { emoji: "🧽", keywords: "sponge" },
      { emoji: "🪑", keywords: "chair" },
      { emoji: "🛋️", keywords: "couch and lamp" },
      { emoji: "🛏️", keywords: "bed" },
      { emoji: "🛌", keywords: "person in bed", tone: true },
      { emoji: "🚪", keywords: "door" },
      { emoji: "🪟", keywords: "window" },
      { emoji: "🪞", keywords: "mirror" },
      { emoji: "🛁", keywords: "bathtub" },
      { emoji: "🚿", keywords: "shower" },
      { emoji: "🚽", keywords: "toilet" },
      { emoji: "🪠", keywords: "plunger" },
      { emoji: "🧴", keywords: "lotion bottle" },
      { emoji: "🛒", keywords: "shopping cart" },
      { emoji: "🛍️", keywords: "shopping bags" },
      { emoji: "🎁", keywords: "gift wrapped" },
      { emoji: "🎀", keywords: "ribbon" },
      { emoji: "🎊", keywords: "confetti ball" },
      { emoji: "🎉", keywords: "party popper" },
      { emoji: "🎈", keywords: "balloon" },
      { emoji: "🪅", keywords: "piñata" },
      { emoji: "📚", keywords: "books" },
      { emoji: "📖", keywords: "open book" },
      { emoji: "📓", keywords: "notebook" },
      { emoji: "📔", keywords: "notebook decorative" },
      { emoji: "📒", keywords: "ledger" },
      { emoji: "📕", keywords: "closed book red" },
      { emoji: "📗", keywords: "green book" },
      { emoji: "📘", keywords: "blue book" },
      { emoji: "📙", keywords: "orange book" },
      { emoji: "📑", keywords: "bookmark tabs" },
      { emoji: "🔖", keywords: "bookmark" },
      { emoji: "📰", keywords: "newspaper" },
      { emoji: "📝", keywords: "memo writing" },
      { emoji: "🖊️", keywords: "pen" },
      { emoji: "🖋️", keywords: "fountain pen" },
      { emoji: "✒️", keywords: "black nib pen" },
      { emoji: "🖌️", keywords: "paintbrush" },
      { emoji: "🖍️", keywords: "crayon" },
      { emoji: "📋", keywords: "clipboard" },
      { emoji: "📌", keywords: "pushpin" },
      { emoji: "📍", keywords: "round pushpin" },
      { emoji: "📎", keywords: "paperclip" },
      { emoji: "🖇️", keywords: "linked paperclips" },
      { emoji: "📏", keywords: "straight ruler" },
      { emoji: "📐", keywords: "triangular ruler" },
      { emoji: "✂️", keywords: "scissors" },
      { emoji: "🗃️", keywords: "card file box" },
      { emoji: "🗄️", keywords: "file cabinet" },
      { emoji: "🗑️", keywords: "wastebasket trash" },
      { emoji: "🔒", keywords: "locked" },
      { emoji: "🔓", keywords: "unlocked" },
      { emoji: "🔏", keywords: "locked with pen" },
      { emoji: "🔐", keywords: "locked with key" },
      { emoji: "🔑", keywords: "key" },
      { emoji: "🗝️", keywords: "old key" },
    ],
  },
  {
    id: "symbols",
    name: "Symbols",
    emojis: [
      { emoji: "❤️", keywords: "heart red love" },
      { emoji: "🧡", keywords: "orange heart" },
      { emoji: "💛", keywords: "yellow heart" },
      { emoji: "💚", keywords: "green heart" },
      { emoji: "💙", keywords: "blue heart" },
      { emoji: "💜", keywords: "purple heart" },
      { emoji: "🖤", keywords: "black heart" },
      { emoji: "🤍", keywords: "white heart" },
      { emoji: "🤎", keywords: "brown heart" },
      { emoji: "💔", keywords: "broken heart" },
      { emoji: "❣️", keywords: "heart exclamation" },
      { emoji: "💕", keywords: "two hearts" },
      { emoji: "💞", keywords: "revolving hearts" },
      { emoji: "💓", keywords: "beating heart" },
      { emoji: "💗", keywords: "growing heart" },
      { emoji: "💖", keywords: "sparkling heart" },
      { emoji: "💘", keywords: "heart arrow cupid" },
      { emoji: "💝", keywords: "heart with ribbon gift" },
      { emoji: "💟", keywords: "heart decoration" },
      { emoji: "☮️", keywords: "peace symbol" },
      { emoji: "✝️", keywords: "latin cross" },
      { emoji: "☪️", keywords: "star and crescent" },
      { emoji: "🕉️", keywords: "om" },
      { emoji: "☸️", keywords: "wheel of dharma" },
      { emoji: "✡️", keywords: "star of david" },
      { emoji: "🔯", keywords: "dotted six pointed star" },
      { emoji: "🕎", keywords: "menorah" },
      { emoji: "☯️", keywords: "yin yang" },
      { emoji: "☦️", keywords: "orthodox cross" },
      { emoji: "🛐", keywords: "place of worship" },
      { emoji: "⛎", keywords: "ophiuchus" },
      { emoji: "♈", keywords: "aries" },
      { emoji: "♉", keywords: "taurus" },
      { emoji: "♊", keywords: "gemini" },
      { emoji: "♋", keywords: "cancer" },
      { emoji: "♌", keywords: "leo" },
      { emoji: "♍", keywords: "virgo" },
      { emoji: "♎", keywords: "libra" },
      { emoji: "♏", keywords: "scorpio" },
      { emoji: "♐", keywords: "sagittarius" },
      { emoji: "♑", keywords: "capricorn" },
      { emoji: "♒", keywords: "aquarius" },
      { emoji: "♓", keywords: "pisces" },
      { emoji: "🆔", keywords: "id button" },
      { emoji: "⚛️", keywords: "atom symbol" },
      { emoji: "🉑", keywords: "japanese acceptable" },
      { emoji: "☢️", keywords: "radioactive" },
      { emoji: "☣️", keywords: "biohazard" },
      { emoji: "📴", keywords: "mobile phone off" },
      { emoji: "📳", keywords: "vibration mode" },
      { emoji: "🈶", keywords: "japanese not free" },
      { emoji: "🈚", keywords: "japanese free of charge" },
      { emoji: "🈸", keywords: "japanese application" },
      { emoji: "🈺", keywords: "japanese open for business" },
      { emoji: "🈷️", keywords: "japanese monthly amount" },
      { emoji: "✴️", keywords: "eight pointed star" },
      { emoji: "🆚", keywords: "vs button" },
      { emoji: "💮", keywords: "white flower" },
      { emoji: "🉐", keywords: "japanese bargain" },
      { emoji: "㊙️", keywords: "japanese secret" },
      { emoji: "㊗️", keywords: "japanese congratulations" },
      { emoji: "🈴", keywords: "japanese passing grade" },
      { emoji: "🈵", keywords: "japanese no vacancy" },
      { emoji: "🈹", keywords: "japanese discount" },
      { emoji: "🈲", keywords: "japanese prohibited" },
      { emoji: "🅰️", keywords: "a button blood type" },
      { emoji: "🅱️", keywords: "b button blood type" },
      { emoji: "🆎", keywords: "ab button blood type" },
      { emoji: "🆑", keywords: "cl button" },
      { emoji: "🅾️", keywords: "o button blood type" },
      { emoji: "🆘", keywords: "sos button" },
      { emoji: "❌", keywords: "cross mark x" },
      { emoji: "⭕", keywords: "hollow red circle" },
      { emoji: "🛑", keywords: "stop sign" },
      { emoji: "⛔", keywords: "no entry" },
      { emoji: "📛", keywords: "name badge" },
      { emoji: "🚫", keywords: "prohibited" },
      { emoji: "💯", keywords: "hundred points" },
      { emoji: "💢", keywords: "anger symbol" },
      { emoji: "♨️", keywords: "hot springs" },
      { emoji: "🚷", keywords: "no pedestrians" },
      { emoji: "🚯", keywords: "no littering" },
      { emoji: "🚳", keywords: "no bicycles" },
      { emoji: "🚱", keywords: "non-potable water" },
      { emoji: "🔞", keywords: "no one under eighteen" },
      { emoji: "📵", keywords: "no mobile phones" },
      { emoji: "🚭", keywords: "no smoking" },
      { emoji: "❗", keywords: "exclamation mark" },
      { emoji: "❕", keywords: "white exclamation mark" },
      { emoji: "❓", keywords: "question mark" },
      { emoji: "❔", keywords: "white question mark" },
      { emoji: "‼️", keywords: "double exclamation" },
      { emoji: "⁉️", keywords: "exclamation question" },
      { emoji: "🔅", keywords: "dim button" },
      { emoji: "🔆", keywords: "bright button" },
      { emoji: "〽️", keywords: "part alternation" },
      { emoji: "⚠️", keywords: "warning" },
      { emoji: "🚸", keywords: "children crossing" },
      { emoji: "🔱", keywords: "trident emblem" },
      { emoji: "⚜️", keywords: "fleur-de-lis" },
      { emoji: "🔰", keywords: "japanese symbol for beginner" },
      { emoji: "♻️", keywords: "recycling" },
      { emoji: "✅", keywords: "check mark button" },
      { emoji: "🈯", keywords: "japanese reserved" },
      { emoji: "💹", keywords: "chart increasing yen" },
      { emoji: "❇️", keywords: "sparkle" },
      { emoji: "✳️", keywords: "eight-spoked asterisk" },
      { emoji: "❎", keywords: "cross mark button" },
      { emoji: "🌐", keywords: "globe with meridians" },
      { emoji: "💠", keywords: "diamond with dot" },
      { emoji: "Ⓜ️", keywords: "circled m" },
      { emoji: "🌀", keywords: "cyclone" },
      { emoji: "💤", keywords: "zzz sleep" },
      { emoji: "🏧", keywords: "atm sign" },
      { emoji: "🚾", keywords: "water closet" },
      { emoji: "♿", keywords: "wheelchair" },
      { emoji: "🅿️", keywords: "p button parking" },
      { emoji: "🈳", keywords: "japanese vacancy" },
      { emoji: "🈂️", keywords: "japanese service" },
      { emoji: "🛂", keywords: "passport control" },
      { emoji: "🛃", keywords: "customs" },
      { emoji: "🛄", keywords: "baggage claim" },
      { emoji: "🛅", keywords: "left luggage" },
      { emoji: "🚹", keywords: "men's room" },
      { emoji: "🚺", keywords: "women's room" },
      { emoji: "🚼", keywords: "baby symbol" },
      { emoji: "🚻", keywords: "restroom" },
      { emoji: "🚮", keywords: "litter in bin" },
      { emoji: "🎦", keywords: "cinema" },
      { emoji: "📶", keywords: "antenna bars signal" },
      { emoji: "🈁", keywords: "japanese here" },
      { emoji: "🔣", keywords: "input symbols" },
      { emoji: "ℹ️", keywords: "information" },
      { emoji: "🔤", keywords: "input latin letters" },
      { emoji: "🔡", keywords: "input lowercase" },
      { emoji: "🔠", keywords: "input uppercase" },
      { emoji: "🆖", keywords: "ng button" },
      { emoji: "🆗", keywords: "ok button" },
      { emoji: "🆙", keywords: "up button" },
      { emoji: "🆒", keywords: "cool button" },
      { emoji: "🆕", keywords: "new button" },
      { emoji: "🆓", keywords: "free button" },
      { emoji: "0️⃣", keywords: "zero" },
      { emoji: "1️⃣", keywords: "one" },
      { emoji: "2️⃣", keywords: "two" },
      { emoji: "3️⃣", keywords: "three" },
      { emoji: "4️⃣", keywords: "four" },
      { emoji: "5️⃣", keywords: "five" },
      { emoji: "6️⃣", keywords: "six" },
      { emoji: "7️⃣", keywords: "seven" },
      { emoji: "8️⃣", keywords: "eight" },
      { emoji: "9️⃣", keywords: "nine" },
      { emoji: "🔟", keywords: "keycap ten" },
      { emoji: "🔢", keywords: "input numbers" },
      { emoji: "#️⃣", keywords: "keycap hash" },
      { emoji: "*️⃣", keywords: "keycap asterisk" },
      { emoji: "⏏️", keywords: "eject" },
      { emoji: "▶️", keywords: "play" },
      { emoji: "⏸️", keywords: "pause" },
      { emoji: "⏯️", keywords: "play or pause" },
      { emoji: "⏹️", keywords: "stop" },
      { emoji: "⏺️", keywords: "record" },
      { emoji: "⏭️", keywords: "next" },
      { emoji: "⏮️", keywords: "previous" },
      { emoji: "⏩", keywords: "fast forward" },
      { emoji: "⏪", keywords: "fast reverse" },
      { emoji: "⏫", keywords: "fast up" },
      { emoji: "⏬", keywords: "fast down" },
      { emoji: "◀️", keywords: "reverse play" },
      { emoji: "🔼", keywords: "up button triangle" },
      { emoji: "🔽", keywords: "down button triangle" },
    ],
  },
  {
    id: "flags",
    name: "Flags",
    emojis: [
      { emoji: "🏳️", keywords: "white flag" },
      { emoji: "🏴", keywords: "black flag" },
      { emoji: "🏁", keywords: "checkered flag" },
      { emoji: "🚩", keywords: "triangular flag" },
      { emoji: "🏳️‍🌈", keywords: "rainbow flag pride" },
      { emoji: "🏳️‍⚧️", keywords: "transgender flag" },
      { emoji: "🏴‍☠️", keywords: "pirate flag" },
      { emoji: "🇺🇸", keywords: "united states us flag" },
      { emoji: "🇬🇧", keywords: "united kingdom uk flag" },
      { emoji: "🇪🇸", keywords: "spain flag" },
      { emoji: "🇫🇷", keywords: "france flag" },
      { emoji: "🇩🇪", keywords: "germany flag" },
      { emoji: "🇮🇹", keywords: "italy flag" },
      { emoji: "🇯🇵", keywords: "japan flag" },
      { emoji: "🇰🇷", keywords: "south korea flag" },
      { emoji: "🇨🇳", keywords: "china flag" },
      { emoji: "🇮🇳", keywords: "india flag" },
      { emoji: "🇧🇷", keywords: "brazil flag" },
      { emoji: "🇲🇽", keywords: "mexico flag" },
      { emoji: "🇨🇦", keywords: "canada flag" },
      { emoji: "🇦🇺", keywords: "australia flag" },
      { emoji: "🇳🇱", keywords: "netherlands flag" },
      { emoji: "🇧🇪", keywords: "belgium flag" },
      { emoji: "🇨🇭", keywords: "switzerland flag" },
      { emoji: "🇸🇪", keywords: "sweden flag" },
      { emoji: "🇳🇴", keywords: "norway flag" },
      { emoji: "🇩🇰", keywords: "denmark flag" },
      { emoji: "🇫🇮", keywords: "finland flag" },
      { emoji: "🇮🇪", keywords: "ireland flag" },
      { emoji: "🇵🇹", keywords: "portugal flag" },
      { emoji: "🇬🇷", keywords: "greece flag" },
      { emoji: "🇵🇱", keywords: "poland flag" },
      { emoji: "🇨🇿", keywords: "czech flag" },
      { emoji: "🇦🇹", keywords: "austria flag" },
      { emoji: "🇷🇺", keywords: "russia flag" },
      { emoji: "🇹🇷", keywords: "turkey flag" },
      { emoji: "🇮🇱", keywords: "israel flag" },
      { emoji: "🇸🇦", keywords: "saudi arabia flag" },
      { emoji: "🇦🇪", keywords: "uae flag emirates" },
      { emoji: "🇿🇦", keywords: "south africa flag" },
      { emoji: "🇪🇬", keywords: "egypt flag" },
      { emoji: "🇦🇷", keywords: "argentina flag" },
      { emoji: "🇨🇱", keywords: "chile flag" },
      { emoji: "🇨🇴", keywords: "colombia flag" },
      { emoji: "🇵🇪", keywords: "peru flag" },
      { emoji: "🇻🇪", keywords: "venezuela flag" },
      { emoji: "🇳🇿", keywords: "new zealand flag" },
      { emoji: "🇸🇬", keywords: "singapore flag" },
      { emoji: "🇲🇾", keywords: "malaysia flag" },
      { emoji: "🇮🇩", keywords: "indonesia flag" },
      { emoji: "🇵🇭", keywords: "philippines flag" },
      { emoji: "🇹🇭", keywords: "thailand flag" },
      { emoji: "🇻🇳", keywords: "vietnam flag" },
    ],
  },
];
/* eslint-enable max-lines */
