/**
 * Curated lucide-react-native icons for the page icon picker.
 *
 * The full icon set is >1500 components and importing it dynamically blows
 * the Metro bundle. We pick a focused set that covers most page-icon needs
 * (docs, projects, areas, common subjects) and let users fall back to emoji
 * for anything missing.
 */

import {
  Activity,
  Airplay,
  AlarmClock,
  Album,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Aperture,
  Archive,
  Award,
  Backpack,
  Banknote,
  BarChart,
  BatteryFull,
  Beaker,
  Bell,
  Bike,
  Bird,
  Bitcoin,
  Bluetooth,
  Bolt,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Brush,
  Bug,
  Building,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckSquare,
  Cherry,
  CircleHelp,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Construction,
  Cookie,
  Cpu,
  CreditCard,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dog,
  Download,
  Droplet,
  Drum,
  Dumbbell,
  Earth,
  Egg,
  Feather,
  File as FileIcon,
  FileText,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  Flower,
  Folder,
  Footprints,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Grape,
  Grid,
  Hammer,
  Hand,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Highlighter,
  Home,
  IceCream,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Lock,
  LogIn,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PanelLeft,
  Paperclip,
  Pause,
  Pen,
  Pencil,
  Phone,
  PieChart,
  Pizza,
  Plane,
  Play,
  Plug,
  Plus,
  Printer,
  Puzzle,
  Quote,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  Rocket,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Sword,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  Trash,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wand,
  Watch,
  Wifi,
  Wind,
  Wrench,
  Zap,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";

export interface LucideIconEntry {
  name: string;
  Icon: LucideIcon;
  /** Lowercased search keywords. */
  keywords: string;
}

/**
 * Ordered list. `name` is what we encode into `Page.icon` as `icon:<name>`.
 * Keep `name` lowercase-kebab to keep the URI tidy.
 */
export const LUCIDE_ICONS: ReadonlyArray<LucideIconEntry> = [
  { name: "activity", Icon: Activity, keywords: "activity pulse heart" },
  { name: "airplay", Icon: Airplay, keywords: "airplay cast" },
  { name: "alarm-clock", Icon: AlarmClock, keywords: "alarm clock time" },
  { name: "album", Icon: Album, keywords: "album music" },
  { name: "alert-circle", Icon: AlertCircle, keywords: "alert warning" },
  { name: "alert-triangle", Icon: AlertTriangle, keywords: "alert warning" },
  { name: "anchor", Icon: Anchor, keywords: "anchor boat sea" },
  { name: "aperture", Icon: Aperture, keywords: "aperture camera" },
  { name: "archive", Icon: Archive, keywords: "archive box" },
  { name: "award", Icon: Award, keywords: "award trophy prize" },
  { name: "backpack", Icon: Backpack, keywords: "backpack school" },
  { name: "banknote", Icon: Banknote, keywords: "money cash bank" },
  { name: "bar-chart", Icon: BarChart, keywords: "chart graph bars" },
  { name: "battery-full", Icon: BatteryFull, keywords: "battery charge" },
  { name: "beaker", Icon: Beaker, keywords: "beaker science lab" },
  { name: "bell", Icon: Bell, keywords: "bell notification" },
  { name: "bike", Icon: Bike, keywords: "bike bicycle" },
  { name: "bird", Icon: Bird, keywords: "bird animal" },
  { name: "bitcoin", Icon: Bitcoin, keywords: "bitcoin crypto" },
  { name: "bluetooth", Icon: Bluetooth, keywords: "bluetooth wireless" },
  { name: "bolt", Icon: Bolt, keywords: "bolt power" },
  { name: "book", Icon: Book, keywords: "book read" },
  { name: "book-open", Icon: BookOpen, keywords: "book open read" },
  { name: "bookmark", Icon: Bookmark, keywords: "bookmark save" },
  { name: "box", Icon: Box, keywords: "box package" },
  { name: "briefcase", Icon: Briefcase, keywords: "briefcase work job" },
  { name: "brush", Icon: Brush, keywords: "brush paint art" },
  { name: "bug", Icon: Bug, keywords: "bug insect issue" },
  { name: "building", Icon: Building, keywords: "building office" },
  { name: "bus", Icon: Bus, keywords: "bus transport" },
  { name: "cake", Icon: Cake, keywords: "cake birthday" },
  { name: "calculator", Icon: Calculator, keywords: "calculator math" },
  { name: "calendar", Icon: Calendar, keywords: "calendar date" },
  { name: "camera", Icon: Camera, keywords: "camera photo" },
  { name: "car", Icon: Car, keywords: "car vehicle" },
  { name: "cat", Icon: Cat, keywords: "cat animal pet" },
  { name: "chart-bar", Icon: ChartBar, keywords: "chart bars graph" },
  { name: "chart-line", Icon: ChartLine, keywords: "chart line graph" },
  { name: "chart-pie", Icon: ChartPie, keywords: "chart pie" },
  { name: "check", Icon: Check, keywords: "check yes" },
  { name: "check-square", Icon: CheckSquare, keywords: "check task done" },
  { name: "cherry", Icon: Cherry, keywords: "cherry fruit" },
  { name: "circle-help", Icon: CircleHelp, keywords: "help question" },
  { name: "clipboard", Icon: Clipboard, keywords: "clipboard copy" },
  { name: "clock", Icon: Clock, keywords: "clock time" },
  { name: "cloud", Icon: Cloud, keywords: "cloud weather sky" },
  { name: "coffee", Icon: Coffee, keywords: "coffee drink" },
  { name: "coins", Icon: Coins, keywords: "coins money" },
  { name: "compass", Icon: Compass, keywords: "compass direction" },
  { name: "construction", Icon: Construction, keywords: "construction build" },
  { name: "cookie", Icon: Cookie, keywords: "cookie snack" },
  { name: "cpu", Icon: Cpu, keywords: "cpu chip computer" },
  { name: "credit-card", Icon: CreditCard, keywords: "credit card payment" },
  { name: "crown", Icon: Crown, keywords: "crown king queen royal" },
  { name: "cup-soda", Icon: CupSoda, keywords: "cup drink mug soda" },
  { name: "database", Icon: Database, keywords: "database storage" },
  { name: "diamond", Icon: Diamond, keywords: "diamond gem" },
  { name: "dog", Icon: Dog, keywords: "dog animal pet" },
  { name: "download", Icon: Download, keywords: "download save" },
  { name: "droplet", Icon: Droplet, keywords: "droplet water" },
  { name: "drum", Icon: Drum, keywords: "drum music instrument" },
  { name: "dumbbell", Icon: Dumbbell, keywords: "dumbbell gym fitness" },
  { name: "earth", Icon: Earth, keywords: "earth world planet" },
  { name: "egg", Icon: Egg, keywords: "egg food" },
  { name: "feather", Icon: Feather, keywords: "feather light write" },
  { name: "file", Icon: FileIcon, keywords: "file document" },
  { name: "file-text", Icon: FileText, keywords: "file text document" },
  { name: "film", Icon: Film, keywords: "film movie video" },
  { name: "filter", Icon: Filter, keywords: "filter sort" },
  { name: "fish", Icon: Fish, keywords: "fish animal" },
  { name: "flag", Icon: Flag, keywords: "flag mark" },
  { name: "flame", Icon: Flame, keywords: "flame fire hot" },
  { name: "flower", Icon: Flower, keywords: "flower plant" },
  { name: "folder", Icon: Folder, keywords: "folder directory" },
  { name: "footprints", Icon: Footprints, keywords: "footprints steps walk" },
  { name: "gamepad-2", Icon: Gamepad2, keywords: "gamepad game" },
  { name: "gauge", Icon: Gauge, keywords: "gauge meter" },
  { name: "gem", Icon: Gem, keywords: "gem diamond stone" },
  { name: "gift", Icon: Gift, keywords: "gift present" },
  { name: "globe", Icon: Globe, keywords: "globe world" },
  { name: "graduation-cap", Icon: GraduationCap, keywords: "graduation cap school" },
  { name: "grape", Icon: Grape, keywords: "grape fruit" },
  { name: "grid", Icon: Grid, keywords: "grid layout" },
  { name: "hammer", Icon: Hammer, keywords: "hammer tool build" },
  { name: "hand", Icon: Hand, keywords: "hand wave" },
  { name: "hard-drive", Icon: HardDrive, keywords: "hard drive disk" },
  { name: "hash", Icon: Hash, keywords: "hash tag number" },
  { name: "headphones", Icon: Headphones, keywords: "headphones music" },
  { name: "heart", Icon: Heart, keywords: "heart love" },
  { name: "help-circle", Icon: HelpCircle, keywords: "help question" },
  { name: "highlighter", Icon: Highlighter, keywords: "highlighter mark" },
  { name: "home", Icon: Home, keywords: "home house" },
  { name: "ice-cream", Icon: IceCream, keywords: "ice cream dessert" },
  { name: "inbox", Icon: Inbox, keywords: "inbox mail" },
  { name: "infinity", Icon: InfinityIcon, keywords: "infinity loop" },
  { name: "info", Icon: Info, keywords: "info information" },
  { name: "key", Icon: Key, keywords: "key unlock" },
  { name: "keyboard", Icon: Keyboard, keywords: "keyboard type" },
  { name: "lamp", Icon: Lamp, keywords: "lamp light" },
  { name: "laptop", Icon: Laptop, keywords: "laptop computer" },
  { name: "leaf", Icon: Leaf, keywords: "leaf plant nature" },
  { name: "library", Icon: Library, keywords: "library books" },
  { name: "life-buoy", Icon: LifeBuoy, keywords: "life buoy help support" },
  { name: "lightbulb", Icon: Lightbulb, keywords: "lightbulb idea" },
  { name: "link", Icon: Link, keywords: "link url" },
  { name: "lock", Icon: Lock, keywords: "lock secure" },
  { name: "log-in", Icon: LogIn, keywords: "login enter" },
  { name: "mail", Icon: Mail, keywords: "mail email" },
  { name: "map", Icon: MapIcon, keywords: "map travel" },
  { name: "map-pin", Icon: MapPin, keywords: "map pin location" },
  { name: "medal", Icon: Medal, keywords: "medal award" },
  { name: "megaphone", Icon: Megaphone, keywords: "megaphone announce" },
  { name: "message-circle", Icon: MessageCircle, keywords: "message chat" },
  { name: "mic", Icon: Mic, keywords: "mic microphone voice" },
  { name: "monitor", Icon: Monitor, keywords: "monitor screen" },
  { name: "moon", Icon: Moon, keywords: "moon night dark" },
  { name: "mountain", Icon: Mountain, keywords: "mountain travel" },
  { name: "mouse", Icon: Mouse, keywords: "mouse computer" },
  { name: "music", Icon: Music, keywords: "music note" },
  { name: "newspaper", Icon: Newspaper, keywords: "newspaper news" },
  { name: "notebook", Icon: Notebook, keywords: "notebook journal" },
  { name: "package", Icon: Package, keywords: "package box" },
  { name: "palette", Icon: Palette, keywords: "palette art color" },
  { name: "panel-left", Icon: PanelLeft, keywords: "panel sidebar" },
  { name: "paperclip", Icon: Paperclip, keywords: "paperclip attach" },
  { name: "pause", Icon: Pause, keywords: "pause stop" },
  { name: "pen", Icon: Pen, keywords: "pen write" },
  { name: "pencil", Icon: Pencil, keywords: "pencil write edit" },
  { name: "phone", Icon: Phone, keywords: "phone call" },
  { name: "pie-chart", Icon: PieChart, keywords: "pie chart" },
  { name: "pizza", Icon: Pizza, keywords: "pizza food" },
  { name: "plane", Icon: Plane, keywords: "plane flight travel" },
  { name: "play", Icon: Play, keywords: "play start" },
  { name: "plug", Icon: Plug, keywords: "plug power" },
  { name: "plus", Icon: Plus, keywords: "plus add" },
  { name: "printer", Icon: Printer, keywords: "printer print" },
  { name: "puzzle", Icon: Puzzle, keywords: "puzzle piece" },
  { name: "quote", Icon: Quote, keywords: "quote citation" },
  { name: "radio", Icon: Radio, keywords: "radio audio" },
  { name: "rainbow", Icon: Rainbow, keywords: "rainbow color" },
  { name: "receipt", Icon: Receipt, keywords: "receipt invoice" },
  { name: "recycle", Icon: Recycle, keywords: "recycle eco" },
  { name: "rocket", Icon: Rocket, keywords: "rocket launch" },
  { name: "save", Icon: Save, keywords: "save disk" },
  { name: "scissors", Icon: Scissors, keywords: "scissors cut" },
  { name: "search", Icon: Search, keywords: "search find" },
  { name: "send", Icon: Send, keywords: "send share" },
  { name: "server", Icon: Server, keywords: "server hosting" },
  { name: "settings", Icon: Settings, keywords: "settings gear" },
  { name: "share", Icon: Share, keywords: "share send" },
  { name: "shield", Icon: Shield, keywords: "shield security" },
  { name: "ship", Icon: Ship, keywords: "ship boat" },
  { name: "shopping-bag", Icon: ShoppingBag, keywords: "shopping bag" },
  { name: "shopping-cart", Icon: ShoppingCart, keywords: "cart shopping" },
  { name: "smile", Icon: Smile, keywords: "smile happy" },
  { name: "snowflake", Icon: Snowflake, keywords: "snow winter" },
  { name: "sparkles", Icon: Sparkles, keywords: "sparkles magic" },
  { name: "speaker", Icon: Speaker, keywords: "speaker sound" },
  { name: "star", Icon: Star, keywords: "star favorite" },
  { name: "sun", Icon: Sun, keywords: "sun day light" },
  { name: "sword", Icon: Sword, keywords: "sword weapon" },
  { name: "tag", Icon: Tag, keywords: "tag label" },
  { name: "target", Icon: Target, keywords: "target goal aim" },
  { name: "terminal", Icon: Terminal, keywords: "terminal console" },
  { name: "thermometer", Icon: Thermometer, keywords: "thermometer temperature" },
  { name: "thumbs-up", Icon: ThumbsUp, keywords: "thumbs up like" },
  { name: "ticket", Icon: Ticket, keywords: "ticket event" },
  { name: "timer", Icon: Timer, keywords: "timer countdown" },
  { name: "train", Icon: Train, keywords: "train transport" },
  { name: "trash", Icon: Trash, keywords: "trash delete" },
  { name: "tree-pine", Icon: TreePine, keywords: "tree nature" },
  { name: "trending-up", Icon: TrendingUp, keywords: "trending up growth" },
  { name: "trophy", Icon: Trophy, keywords: "trophy award win" },
  { name: "truck", Icon: Truck, keywords: "truck delivery" },
  { name: "tv", Icon: Tv, keywords: "tv television" },
  { name: "umbrella", Icon: Umbrella, keywords: "umbrella rain" },
  { name: "upload", Icon: Upload, keywords: "upload send" },
  { name: "user", Icon: User, keywords: "user person" },
  { name: "users", Icon: Users, keywords: "users team" },
  { name: "utensils", Icon: Utensils, keywords: "utensils food restaurant" },
  { name: "video", Icon: Video, keywords: "video camera record" },
  { name: "wallet", Icon: Wallet, keywords: "wallet money" },
  { name: "wand", Icon: Wand, keywords: "wand magic" },
  { name: "watch", Icon: Watch, keywords: "watch time" },
  { name: "wifi", Icon: Wifi, keywords: "wifi network" },
  { name: "wind", Icon: Wind, keywords: "wind weather" },
  { name: "wrench", Icon: Wrench, keywords: "wrench tool" },
  { name: "zap", Icon: Zap, keywords: "zap energy lightning" },
];

const LUCIDE_BY_NAME = new Map<string, LucideIcon>(
  LUCIDE_ICONS.map((entry) => [entry.name, entry.Icon]),
);

/** Lookup helper used by IconDisplay to render a stored `icon:<name>` value. */
export function getLucideIcon(name: string): LucideIcon | null {
  return LUCIDE_BY_NAME.get(name) ?? null;
}
